### ISSUE TITLE
Formatting for JSE

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/teaching_responsibility#11]
We should look to see if the Journal for Stat Ed has a Rmd theme/template. If not, perhaps we can see if we can follow the formatting of an open paper recently published there? Such as this one: https://github.com/mine-cetinkaya-rundel/fresh-ds

**Comment by ttimbers** [comment]
Here are the details for the special issue submission: https://nhorton.people.amherst.edu/call_reproducibility.pdf

**Comment by joelostblom** [comment]
[Journal for Stat Ed refers to the American Statistical Association's style guide](https://www.tandfonline.com/action/authorSubmission?show=instructions&journalCode=ujse21&utm_source=CPB&utm_medium=cms&utm_campaign=JPG15743#style), so I am using an R Markdown template for ASA that I found in the `rticles` package while double checking the specifics in Journal for Stat Ed and adjusting any differences.

**Comment by joelostblom** [comment]
Unfortunately the rticles template seem to lack support for basic markdown syntax such as tables and figure crossreferencing. I spent some time trying to fix this for the ASA template but I don't think it is worthwhile and will use the bookdown output format you used and add any style changes manually.
