### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/teaching_responsibility#18]
_"This outlook is likely at least in part motivated by fact that these
processes do not directly lead to novel insights in the same way as a predictive
model might"_ > _"This outlook is likely at least in part motivated by fact that these
processes do**es** not directly lead to novel insights in the same way as a predictive
model might"_

**Comment by ttimbers** [comment]
In Fig 2 legend: "Latex" should be "LaTeX".

**Comment by joelostblom** [comment]
I have fixed the "latex" typo in #38. For your first comment here I think the MS is already correct since "processes" is plural so it should say "...these processes do..." rather than "...these processes does...".
