### ISSUE TITLE
Create better example for Example lesson of letting them fail (in a controlled manner)

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/teaching_responsibility#2]
I plan on using the [`breast_cancer_predictor`](https://github.com/ttimbers/breast_cancer_predictor) analysis pipeline for this next year. We should link to that in this manuscript in place of what I have currently linked to. Note: I plan to recode this all in Python, and I plan to make two separate repos instead of a release of the same repo.

**Comment by joelostblom** [comment]
I am not sure how to add this since there are two referenced repos in the text, one for the irreproducible and one for the reproducible analysis, but the breast cancer example is just one repo, so I will let you add this in the way you were planning.

**Comment by ttimbers** [comment]
Removed from manuscript. If the reviewers ask for this, we can add it in.
