### ISSUE TITLE
Specify how to implement "Study cases"

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/teaching_responsibility#21]
> In the ‘Study cases…’ sub-section, this struck me as a business school approach, and I wonder if there is a pedagogy-focused literature coming out of business schools that might be worth engaging with? More specifically, I think it would be great to know a little more about how actually implement this – are students expected to read a paper and then there is a test about it? Do they just talk through it?

**Comment by joelostblom** [comment]
@ttimbers Could you elaborate on this with what you did in 310 this year? Would that fit here?

**Comment by ttimbers** [comment]
Here are my notes from that: https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/materials/lectures/01-intro-to-ds-workflows.html#an-example-with-large-impact

This year, I just shared the cases with them to help provide motivation. First case was a case where the consequence was retraction - a significant consequence for academics. The second case was the hospital opening delay to illustrate that non-reproducible analyses can have significant consequences, even outside of academia.

So summaries of the cases were shared. My plan is to ask about these on the midterm. So far I have not assessed the students on this.

What I think could be done better in future with this, is present the case, what went wrong, and ask the students to explain how more reproducible practices could have lead to a different outcome. So a think-pair-share could work here. As could a written question on a lab assignment. Or a class discussion (if the case was assigned as a pre-reading).

Here's an interesting article from Harvard Magazine that discusses the history of cases studies, which originated from Law School and how they have been adopted by Business and Medical schools. I am not sure what we can draw from this article, but it is an interesting read: https://www.harvardmagazine.com/2003/09/making-the-case-html

At this point, we don't have a lot of experience with teaching reproducibility case studies, we are just starting out... So I don't have a lot to say here yet... Maybe we can just state that case studies have been shown to be an effective pedagogy in Law, Business and Medicine (some citations) and we think they could be valuable here. Maybe we could then summarize how business or medicine case studies are often employed in teaching and muse that a similar, or tweaked pedagogy could be useful for teaching reproducibility?
