### ISSUE TITLE
More specifics around "Letting them fail"

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/teaching_responsibility#22]
> Turning to ‘Letting them…’, again I’d love another paragraph worth of details around this. In particular: How much time is devoted to this activity? Where in the term and the broader program is it implemented? And how is it assessed?

**Comment by joelostblom** [comment]
@ttimbers Do you already have a suitable example that we can include as a response to this?

**Comment by ttimbers** [comment]
> How much time is devoted to this activity?

15 - 20 min?

> Where in the term and the broader program is it implemented?

In MDS, this is in workflows, near the middle of the course. Which is near the first third of the program?

> And how is it assessed?

It is not really assessed. Instead progress is tracked (where students are at in the activity) via polls to see how far they got. I have an example of the exercise here (search for Exercise 1:): https://github.ubc.ca/MDS-2019-20/DSCI_522_dsci-workflows_students/blob/master/lectures/08_lecture_conda_and_repro_wrap_up.ipynb
