### ISSUE TITLE
Include a worksheet in the appendix

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/teaching_responsibility#26]
> Turning to the ‘Worksheets’ sub-section, I was very interested in this idea and wonder if there is an example that could be provided, perhaps in an appendix.

**Comment by joelostblom** [comment]
I think your worksheets are more battle-tested and elaborate than mine @ttimbers , which is why I assigned this to you.

**Comment by ttimbers** [comment]
Sure, we could include the version control worksheet from DSCI 100? I thought we already linked to it, but if including it in the appendix is more desirable, we can do that. It can be found here: https://github.com/UBC-DSCI/data-science-a-first-intro-worksheets/blob/main/worksheet_version_control/worksheet_version_control.ipynb

Note: Trevor has some hilarious bolding of commands that we would want to remove I think if we include this in the appendix (and I will talk to him about doing that for this public version as well). These are under "4. Cloning your repository on JupyterHub" and are there so students don't bork their workspaces on the JupyterHub by making their home directories Git repos, for example, and other things. 😂

**Comment by joelostblom** [comment]
You're right, we already provided a link to https://github.com/UBC-DSCI/dsci-100-assets/blob/master/2021-summer/materials/worksheet_05/worksheet_05.ipynb (which has less bolding) in the ms, I will point that out in the review response and close this.
