### ISSUE TITLE
Mention how practice affects top and bottom 10 percent of students

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/teaching_responsibility#28]
> Finally, turning to the ‘Lots of practice’ section, I found the discussion very interesting, although if the paper needs to be trimmed, perhaps these pages – 12-13 – would be place to do it by condensing some of the discussion. More generally, I am wondering how this implementation accounts for the different abilities in the top 10 per cent of the class compared with the bottom 10 per cent or even median. How do the authors engage those different students, with their different needs, when it comes to practice?

I don't think this is anything we have data on, is it?

**Comment by ttimbers** [comment]
I think one thing we do in MDS are the optional exercises in labs for bonus marks - that keeps the keeners engaged and gets them to learn more about reproducibility (or any topic we have on this). 

I think the worksheets help the bottom 10%, but I have no hard evidence on this... Just from block rep and teaching eval feedback, that the worksheets really help prepare the students to do harder lab questions or project work.
