### ISSUE TITLE
Title?

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/teaching_responsibility#5]
@joelostblom - Currently the title is "Teaching reproducibility: motivation, direct instruction and practice" but I think this is more about recommended best practices, so what about "Best practices for teaching reproducibility: motivation, direct instruction and practice"

**Comment by ttimbers** [comment]
I have a new suggestion for a title that I am very chuffed about: "Opinionated practices for teachingreproducibility: motivation, guidedinstruction and practice".

I love Hilary Parker's article "Opinionated analysis" and I am inspired by her title, so drawing from there. Also, this kind of reads like an op ed. What do you think?

**Comment by joelostblom** [comment]
Sounds great to me!

**Comment by ttimbers** [comment]
Great! Since we agree, closing!
