### ISSUE TITLE
Find case studies with real world consequences

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/teaching_responsibility#8]
Some of these are more science or data analysis errors rather then reproducibility, but it is what I found from looking around for a few hours.

- Incorrect encoding of binary variable: https://jamanetwork.com/journals/jama/fullarticle/2752474
- Reproducing a bioinformatics pipeline: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6054242/
- Treating NAs as 0s lead to the retraction of this paper https://www.nature.com/articles/s41586-021-03656-3, code here https://github.com/babeheim/moralizing-gods-reanalysis.
- Paper (600 citations) retracted after questions arose of some images and there was no original data available to reproduce them https://www.nature.com/articles/s41586-020-2112-4?proof=t
- Excel error leads to retraction https://twitter.com/retractionwatch/status/1026550345961431043?lang=en
- Excel error leads to hospital opening delay https://www.bbc.com/news/uk-scotland-edinburgh-east-fife-53893101
- Excel error leads to 16,000 lost covid cases in the UK https://www.bbc.com/news/technology-54423988
- More excel errors here https://www.washingtonpost.com/news/wonk/wp/2016/08/26/an-alarming-number-of-scientific-papers-contain-excel-errors/ and here http://www.eusprig.org/horror-stories.htm
- Gene names mistakes from Excel https://www.ncbi.nlm.nih.gov/pmc/articles/PMC459209/?tool=pubmed

- https://xkcd.com/242/
![image](https://user-images.githubusercontent.com/4560057/127525592-5a02837e-0883-4558-ae1d-8738dda18b0c.png)

**Comment by ttimbers** [comment]
@joelostblom - I will leave this for you to close after you update the table I created.
